source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'TJView_Example', :exclusive => true do
  pod "TJView", :path => "../"
end

target 'TJView_Tests', :exclusive => true do
  pod "TJView", :path => "../"

  
end
